spring:
  datasource:
    password: D4yth0rm3t4l!
    testWhileIdle: true
    url: jdbc:mysql://localhost:3306/Sebas
    username: root
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true